#!/usr/bin/env bash
# install nginx in a new server
sudo apt update
sudo apt -y install nginx
sudo chmod 665/var/www/html/index.nginx-debian.html
sudo chmod 665 /usr/share/nginx/html/index.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Hello World!" > /usr/share/nginx/html/index.html
sudo service nginx restart
