#!/usr/bin/env bash
# a bash script that display a certain word at a certian number index
for number in {1..100}; do
	if [ $((number % 5)) -eq 0 ] && [ $((number % 3)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((number % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((number % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$number"
	fi
done
