#!/usr/bin/env bash
#a bash script tha reads files
filename="/etc/passwd"
while read -r line
do
	username=$(echo "$line" | cut -d ":" -f1)
	group_id=$(echo "$line" | cut -d ":" -f4)
	home_dir=$(echo "$line" | cut -d ":" -f6)
	command_shell=$(echo "$line" | cut -d ":" -f7)
	user_id=$(echo "$line" | cut -d ":" -f3)
	password=$(echo "$line" | cut -d ":" -f2)
	info=$(echo "$line" | cut -d ":" -f5)
	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $command_shell. $user_id's place is protected by the passcode $password, more info about the user here: $info"
done < "$filename"
